/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Token represents a morpheme in the analyzed text.
 *
 * Each token contains the surface form, part-of-speech tag,
 * and position information.
 */
export interface Token {
  /** The surface form (actual text) */
  surface: string
  /** Part-of-speech tag */
  pos: string
  /** Start position in bytes */
  start: number
  /** End position in bytes */
  end: number
  /** Reading (optional) */
  reading?: string
  /** Lemma/base form (optional) */
  lemma?: string
}

/**
 * Mecab is the main interface for Korean morphological analysis.
 *
 * @example
 * ```typescript
 * import { Mecab } from '@mecab-ko/node';
 *
 * const mecab = new Mecab();
 * const tokens = mecab.tokenize('안녕하세요');
 * console.log(tokens);
 * ```
 */
export class Mecab {
  /**
   * Creates a new Mecab instance with the default dictionary.
   *
   * @throws {Error} If the dictionary cannot be loaded or initialized
   *
   * @example
   * ```typescript
   * const mecab = new Mecab();
   * ```
   */
  constructor()

  /**
   * Creates a new Mecab instance with a custom dictionary path.
   *
   * @param dictPath - Path to the dictionary directory
   * @throws {Error} If the dictionary cannot be loaded
   *
   * @example
   * ```typescript
   * const mecab = Mecab.withDict('/path/to/dict');
   * ```
   */
  static withDict(dictPath: string): Mecab

  /**
   * Tokenizes the input text and returns an array of tokens.
   *
   * Each token contains the surface form, part-of-speech tag, and position.
   *
   * @param text - The text to analyze
   * @returns An array of Token objects
   *
   * @example
   * ```typescript
   * const tokens = mecab.tokenize('형태소 분석기');
   * // Returns: [
   * //   { surface: '형태소', pos: 'NNG', start: 0, end: 9, ... },
   * //   { surface: '분석기', pos: 'NNG', start: 12, end: 21, ... }
   * // ]
   * ```
   */
  tokenize(text: string): Array<Token>

  /**
   * Extracts morphemes (surface forms) from the input text.
   *
   * This is equivalent to calling `tokenize` and extracting surface forms.
   *
   * @param text - The text to analyze
   * @returns An array of morpheme strings
   *
   * @example
   * ```typescript
   * const morphs = mecab.morphs('형태소 분석');
   * // Returns: ['형태소', '분석']
   * ```
   */
  morphs(text: string): Array<string>

  /**
   * Extracts nouns from the input text.
   *
   * Returns only tokens whose POS tag starts with 'NN'.
   *
   * @param text - The text to analyze
   * @returns An array of noun strings
   *
   * @example
   * ```typescript
   * const nouns = mecab.nouns('대한민국의 수도는 서울입니다');
   * // Returns: ['대한민국', '수도', '서울']
   * ```
   */
  nouns(text: string): Array<string>

  /**
   * Returns part-of-speech tagged pairs.
   *
   * Each pair consists of [surface, pos].
   *
   * @param text - The text to analyze
   * @returns An array of [surface, pos] tuples
   *
   * @example
   * ```typescript
   * const pairs = mecab.pos('안녕하세요');
   * // Returns: [['안녕하세요', 'NNG']]
   * ```
   */
  pos(text: string): Array<Array<string>>

  /**
   * Parses text and returns MeCab-compatible format string.
   *
   * The output format follows the original MeCab format:
   * ```
   * surface\tfeature1,feature2,...
   * EOS
   * ```
   *
   * @param text - The text to analyze
   * @returns A formatted string in MeCab format
   *
   * @example
   * ```typescript
   * const result = mecab.parse('형태소');
   * console.log(result);
   * // Output:
   * // 형태소\tNNG,*,*,*,*,*,*,*
   * // EOS
   * ```
   */
  parse(text: string): string
}

/**
 * Returns the version of the mecab-ko-node library.
 *
 * @returns The version string
 *
 * @example
 * ```typescript
 * import { getVersion } from '@mecab-ko/node';
 * console.log(getVersion()); // "0.1.0"
 * ```
 */
export function getVersion(): string
