/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Mecab is the main interface for Korean morphological analysis.
 *
 * # Examples
 *
 * ```javascript
 * const { Mecab } = require('@mecab-ko/node');
 *
 * const mecab = new Mecab();
 * const tokens = mecab.tokenize('안녕하세요');
 * console.log(tokens);
 * ```
 */
export declare class Mecab {
  /**
   * Creates a new Mecab instance with the default dictionary.
   *
   * # Errors
   *
   * Returns an error if the dictionary cannot be loaded or initialized.
   *
   * # Examples
   *
   * ```javascript
   * const mecab = new Mecab();
   * ```
   */
  constructor()
  /**
   * Creates a new Mecab instance with a custom dictionary path.
   *
   * # Arguments
   *
   * * `dict_path` - Path to the dictionary directory
   *
   * # Errors
   *
   * Returns an error if the dictionary cannot be loaded.
   *
   * # Examples
   *
   * ```javascript
   * const mecab = Mecab.withDict('/path/to/dict');
   * ```
   */
  static withDict(dictPath: string): Mecab
  /**
   * Tokenizes the input text and returns an array of tokens.
   *
   * Each token contains the surface form, part-of-speech tag, and position.
   *
   * # Arguments
   *
   * * `text` - The text to analyze
   *
   * # Returns
   *
   * An array of Token objects.
   *
   * # Examples
   *
   * ```javascript
   * const tokens = mecab.tokenize('형태소 분석기');
   * // Returns: [
   * //   { surface: '형태소', pos: 'NNG', ... },
   * //   { surface: '분석기', pos: 'NNG', ... }
   * // ]
   * ```
   */
  tokenize(text: string): Array<Token>
  /**
   * Extracts morphemes (surface forms) from the input text.
   *
   * This is equivalent to calling `tokenize` and extracting surface forms.
   *
   * # Arguments
   *
   * * `text` - The text to analyze
   *
   * # Returns
   *
   * An array of morpheme strings.
   *
   * # Examples
   *
   * ```javascript
   * const morphs = mecab.morphs('형태소 분석');
   * // Returns: ['형태소', '분석']
   * ```
   */
  morphs(text: string): Array<string>
  /**
   * Extracts nouns from the input text.
   *
   * Returns only tokens whose POS tag starts with 'NN'.
   *
   * # Arguments
   *
   * * `text` - The text to analyze
   *
   * # Returns
   *
   * An array of noun strings.
   *
   * # Examples
   *
   * ```javascript
   * const nouns = mecab.nouns('대한민국의 수도는 서울입니다');
   * // Returns: ['대한민국', '수도', '서울']
   * ```
   */
  nouns(text: string): Array<string>
  /**
   * Returns part-of-speech tagged pairs.
   *
   * Each pair consists of [surface, pos].
   *
   * # Arguments
   *
   * * `text` - The text to analyze
   *
   * # Returns
   *
   * An array of [surface, pos] tuples.
   *
   * # Examples
   *
   * ```javascript
   * const pairs = mecab.pos('안녕하세요');
   * // Returns: [['안녕하세요', 'NNG']]
   * ```
   */
  pos(text: string): Array<Array<string>>
  /**
   * Parses text and returns MeCab-compatible format string.
   *
   * The output format follows the original `MeCab` format:
   * ```text
   * surface\tfeature1,feature2,...
   * EOS
   * ```
   *
   * # Arguments
   *
   * * `text` - The text to analyze
   *
   * # Returns
   *
   * A formatted string in `MeCab` format.
   *
   * # Examples
   *
   * ```javascript
   * const result = mecab.parse('형태소');
   * console.log(result);
   * // Output:
   * // 형태소\tNNG,*,*,*,*,*,*,*
   * // EOS
   * ```
   */
  parse(text: string): string
}

/**
 * Returns the version of the mecab-ko-node library.
 *
 * # Examples
 *
 * ```javascript
 * const version = getVersion();
 * console.log(version); // "0.1.0"
 */
export declare function getVersion(): string

/**
 * Token represents a morpheme in the analyzed text.
 *
 * Each token contains the surface form, part-of-speech tag,
 * and position information.
 */
export interface Token {
  /** The surface form (actual text) */
  surface: string
  /** Part-of-speech tag */
  pos: string
  /** Start position in bytes */
  start: number
  /** End position in bytes */
  end: number
  /** Reading (optional) */
  reading?: string
  /** Lemma/base form (optional) */
  lemma?: string
}
